# action.yml
name: 'Run Docker Image'
description: 'Docker test'
inputs:
  token: 
    description: 'Github Token'
    required: true
  file_path:
    description: 'File containing list of repos'
    required: true
outputs:
  results: # id of output
    description: 'results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.file_path }}'
    - '${{ inputs.token }}'