# action.yml
name: 'Run Docker Image'
description: 'Docker test'
inputs:
  token: 
    description: 'Github Token'
    required: true
outputs:
  results: # id of output
    description: 'results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # - 'cd ./scripts/ &&'
    # - 'python3' 
    # - './auth_repo_metadata_pull.py' 
    # - '../config/repos_list_dir/repos_list_1.json' 
    # - '-t' 
    - '${{ inputs.token }}'
