# action.yml
name: 'Run Docker Image'
description: 'Docker test'
outputs:
  results: # id of output
    description: 'results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - python3 ./scripts/auth_repo_metadata_pull.py ./config/repos_list_1.json -t ${{ env.GH_TOKEN }}
