name: Repo Metadata Puller for repos_list_5
run-name: Pulling Repo Metadata
on: workflow_dispatch
  # schedule:
  #   - cron: "38 1 * * *"
jobs:
  Run-reusable-metadata-puller:
    uses: ./.github/workflows/reusable-repo-metadata-puller.yml
    with:
      repos_list_path: ../config/repos_list_dir/repos_list_5.json
